### ISSUE TITLE
Bonding curve update for cryptopools

### ISSUE THREAD

**Issue by chanhosuh** [curveresearch/curvesim#148]
There's already a `_get_y` in the cryptopool module, but this is a pure function.  Likely we will want to extend the interface to have a public `get_y` on the pool itself, so functions like `bonding_curve` can easily integrate.

**Update:** there is now a `get_y` method on the cryptopool.  This might mean no work may be required, but this should be checked.  I expect there is something (always is).

**Correction:** replaced references to `get_dy` by `get_y`

**Comment by allt0ld** [comment]
A few changes are needed. Unlike `CryptoPool`, `CurveCryptoPool` doesn't have the `D` method, only the `D` attribute. Also, the `truncate` kwarg for `curvesim.bonding_curve` will cause an error by truncating `D` to the point where the Cryptoswap invariant breaks,
