### ISSUE TITLE
Tricrypto `get_dy` implementation

### ISSUE THREAD

**Issue by chanhosuh** [curveresearch/curvesim#214]
Currently `CurveCryptoPool.get_dy` does not handle 3 coins, only 2.  Update the implementation in a clean manner to handle this.  Similar test as for 2 coins should work.  Reference implementation is the Tricrypto-NG vyper fixture.

**Comment by allt0ld** [comment]
Fixes #148

**Comment by chanhosuh** [comment]
> Fixes #148

Actually #148 doesn't need `get_dy`, it needs `get_y`, which is implemented now.  Also, i think probably the price scale needs to be used to make sure the axis range is correct.
