### ISSUE TITLE
Tricrypto `remove_liquidity_one_coin`

### ISSUE THREAD

**Issue by chanhosuh** [curveresearch/curvesim#218]
Currently `CurveCryptoPool.remove_liquidity_one_coin` does not handle 3 coins, only 2. Update the implementation in a clean manner to handle this. Similar test as for 2 coins should work. Reference implementation is the Tricrypto-NG vyper fixture.

**Note:** This is blocked by `calc_withdraw_one_coin`.

**Comment by allt0ld** [comment]
Tricrypto claims admin fees before withdrawal, but cryptopool doesn't. This difference links this issue to #231
