### ISSUE TITLE
Floating point errors in annualized returns when very short intervals are used

### ISSUE THREAD

**Issue by nagakingg** [curveresearch/curvesim#228]
### Version Information

curvesim 0.5.0.b1, CPython 3.10.12 on Linux

### What's your issue about?

[compute_annualized_returns](https://github.com/curveresearch/curvesim/blob/5ff34ed69c8bb7392a629435d1396e66fb4e0f41/curvesim/metrics/metrics.py#L511) can return wonky results when inter-trade intervals are short (~1 min). I'm assuming this is a floating point issue with the very small values.

### How can it be fixed?
Two options:
- use Decimal to avoid floating point error
- Downsample the time series to hours or days before computing annualized returns

I prefer the former as it allows us to still use all of the data. Thoughts?

**Comment by chanhosuh** [comment]
I think `Decimal` is fine.  It is a bit slower but I don't believe that matters here.

**Comment by allt0ld** [comment]
@nagakingg and I went through the data that was causing this error. Prices used for `_get_pool_value` were encoded in 10**18 precision, which made the numpy `float64`s returned by `_get_value_from_prices` overflow and turn negative. In turn, this data was fed to `compute_annualized_returns`, resulting in negative annualized returns.

As long as pool values are less than 10**18 (1 quintillion) of the "numeraire" coin (usually dollars) at 10**0 precision , this error shouldn't present itself. Nothing needs to be changed.
