### ISSUE TITLE
CryptoPool Sim Finalized Release (0.5.0)

### ISSUE THREAD

**Issue by nagakingg** [curveresearch/curvesim#229]
I compiled a list of issues I encountered when running v2 simulations with high-temporal-frequency data. @chanhosuh and @allt0ld, can you take a look at these and let me know if you have any thoughts on the proposed solutions or alternatives.

- #213 
- #222
- #223
- #224
- #227
- #228

For completeness, I'll also list these bugs:
- #219
- #220
- #221

**Comment by chanhosuh** [comment]
I think we can roll out the next versions like so:

beta version (0.5.0b2):
- #219
- #220
- # 221
- #222
- #213
- #224

release candidate (0.5.0rc1):
- update to use new curve-prices API for the pool volume
- possibly #223, #227, #228

If these block the release, we can wait until 0.5.5 (or an earlier version if we have one):
- #223
- #227 
- #228

**Comment by nagakingg** [comment]
Note: also have to update docs/readme to reflect that the default parameters have been removed. Not sure if anything else needs to be updated?

**Comment by nagakingg** [comment]
It appears these have all been addressed. Feel free to re-open if we missed anything.
