### ISSUE TITLE
Tricrypto `lp_price`

### ISSUE THREAD

**Issue by allt0ld** [curveresearch/curvesim#230]
`CurveCryptoPool.lp_price` hasn't been implemented for 3-coin pools. There's already some TODO logic implemented, which we can comment out. Said logic requires an integer cube root function, which `curvesim.pool.cryptoswap.calcs.tricrypto_ng._cbrt` is.

**Comment by chanhosuh** [comment]
I noticed that for 2-coins, I wrote a somewhat sloppy test that combined testing `lp_price` with price oracle, probably because they both rely on similar time-based logic.  Anyway, you can either copy that or write them as separate tests.  Technically the price oracle should be tested too.
