### ISSUE TITLE
Reinstate `claim_admin_fees` (Cryptoswap)

### ISSUE THREAD

**Issue by chanhosuh** [curveresearch/curvesim#231]
Right now this is disabled since it isn't needed for basic sims.  Activating this requires some care as this is done in different operations for the 2-coin factory cryptopool and the tricrypto-ng pools.

**Comment by allt0ld** [comment]
The tricrypto-ng and 2-coin cryptopool implementations of `_claim_admin_fees` have one main difference. Tricrypto-ng will end execution early (without updating state) if there aren't enough profits to claim. Cryptopool, will, at the very least, still update `D` and `virtual_price` even if there aren't enough profits to claim.

**Comment by allt0ld** [comment]
Another important thing to note: cryptopool calls `_claim_admin_fees` in `tweak_price`, but tricrypto does not. Instead, tricrypto calls `_claim_admin_fees` in functions that call `tweak_price`, with the order varying. Additionally, in tricrypto, `claim_admin_fees` is called several places outside of functions that call `tweak_price`, while in cryptopool, the only relevant `claim_admin_fees` call takes place inside of `tweak_price`.
