### ISSUE TITLE
Standardize output folder names

### ISSUE THREAD

**Issue by chanhosuh** [curveresearch/curvesim#46]
Right now, different `poolname` inputs will create different result folders for the same pool.  Should be standardized somehow, e.g. symbol + 6 char prefix from address, to balance readability with uniqueness.

**Comment by nagakingg** [comment]
Fixed in [b13b19d6365759f38603b6f19bcb7984b4cfe1cc](https://github.com/curveresearch/curvesim/commit/b13b19d6365759f38603b6f19bcb7984b4cfe1cc)
