### ISSUE TITLE
Test Python 3.11 compatibility

### ISSUE THREAD

**Issue by chanhosuh** [curveresearch/curvesim#80]
Might be blocked by this: https://github.com/vyperlang/vyper/pull/3129

**Comment by DamyanBG** [comment]
Hey, if I have just to test and show the result, assign me this.

**Comment by chanhosuh** [comment]
> Hey, if I have just to test and show the result, assign me this.

OK!  Basically what we need is someone to `pip` install the package under 3.11 and put it through the paces, e.g. output some results for several pools (regular stableswap and metapool), and then compare them against the results from an earlier python version (3.8, 3.9, or 3.10).  

You can commit the results to a PR branch and we'll take a look!

**Comment by DamyanBG** [comment]
I have some error when I am trying to install curvesim with pip:

Running setup.py install for lru-dict ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lru-dict did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      C:\Users\death\OneDrive\\u0420\u0430\u0431\u043e\u0442\u0435\u043d \u043f\u043b\u043e\u0442\Development\Contribution\curvit\.venv\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'lru' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lru-dict

note: This is an issue with the package mentioned above, not pip.

I have Microsoft Visual C++ 14.0 or greater installed.

**Comment by DamyanBG** [comment]
Yes, still I have an issue:

Running setup.py install for lru-dict ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lru-dict did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      C:\Users\ddimitr\OneDrive - SoftServe, Inc\Desktop\Testova papka\proba-py-3-11\.venv\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'lru' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lru-dict

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by chanhosuh** [comment]
> I think lru-dict do not have support for Python 3.11

Yeah, looks like: https://stackoverflow.com/a/75901434/1175053

I think it's coming from web3.py: https://github.com/ethereum/web3.py/issues/2884

We might not actually even need web3.py.  Maybe we should look into removing that.
