### ISSUE TITLE
CryptoSwap method get_dy method is not read-only

### ISSUE THREAD

**Issue by keithbaum** [curveresearch/curvesim#97]
Here,

https://github.com/curveresearch/curvesim/blob/5dd5ea165eea2b28efbf0f59612d964ec6459846/curvesim/pool/cryptoswap/pool.py#L580

Code points to balances using xp variable and then increments it without preserving original value.

```
xp: List[int] = self.balances
xp[i] += dx
```

I suggest creating a context preserving pool balances, like so:

```
with self.balance_preservation_context:
    do stuff
```

Where context object hold a copy of pool balances and restores them on `__exit__`

**Comment by chanhosuh** [comment]
Thanks for the catch!
